#+title: Readme File for Underfoot Project

* Underfoot 
** Overview
   Underfoot is a simple game I am making to learn the usage of game programming. I've never done any real game development and this seems like a fun way to do so. Underfoot is developed in python. As of the time of this documentation update I'm using 3.10 because I want to play with match syntax. I could push the reqs up later. I am undecided if I will be using pygame, pyglet or just raw open gl. I want to learn alot about these systems and will likely opt for something lower level if possible.
   Later for another project Maybe I can use say GODOT
** Contributions
   I'm not certain I'll accept PR's and such with this project since its me learning. If I plan to I'll update this. 
** Reference Materials
*** Repo Structure
    I'm using poetry here for the first time and followed loosely https://blog.pronus.io/en/posts/python/how-to-set-up-a-perfect-python-project/ which was easy. Poetry works fine with pyenv. I'm also following the authors information about integrating github actions. We use ADO at work so this will be a fun thing to keep me current. 
*** I will be using the following references as research for my design phase
https://www.youtube.com/watch?v=YVjT0OeE4P0
https://www.youtube.com/c/obiwac
https://stackoverflow.com/questions/35704148/pyopengl-rendering-incorrectly-with-nvidia-fine-with-integrated-graphics
https://www.youtube.com/watch?v=U9Ldr_PeRA8
https://stackabuse.com/brief-introduction-to-opengl-in-python-with-pyopengl/

