# AUTOGENERATED! DO NOT EDIT! File to edit: 02_pygame_learning.ipynb (unless otherwise specified).

__all__ = ['pygame_learning', 'game_actor', 'draw_window', 'colide_animation', 'handle_player_movement', 'main', 'VELO',
           'WHITE', 'NICE_ORANGE', 'main_window', 'FPS', 'NOGO']

# Cell
import pygame
from dataclasses import dataclass
from random import *

class pygame_learning:
    def __init__(self):
        pass

WIDTH,HEIGHT = 900,600
VELO = 3
WHITE = (255,255,255)
NICE_ORANGE = (255,69,2)
main_window = pygame.display.set_mode((WIDTH,HEIGHT))
FPS = 60
NOGO = pygame.Rect(650,300,100,100)
#MAIN_CHARACTER = pygame.transform.rotate(MAIN_CHARACTER,180)

@dataclass
class game_actor:
    name: str
    image_location: str
    size_x: int = 0
    size_y: int = 0
    x: int = 0
    y: int = 0
    actor_rect: pygame.Rect = pygame.Rect(0,0,0,0)

def draw_window(char_list):
    main_window.fill(WHITE)

    pygame.draw.rect(main_window,NICE_ORANGE,NOGO)

    for character in  char_list:
        char_img = pygame.image.load(character.image_location)
        char_img = pygame.transform.scale(char_img,(character.size_x, character.size_y))
        main_window.blit(
            char_img, (character.x, character.y)
        )
    pygame.display.update()

def colide_animation(character,dir_hit):
    if dir_hit == 'LEFT':
        character.x += 25
        character.y += randint(-10,10)
    elif dir_hit == 'RIGHT':
        character.x -= 25
        character.y += randint(-10,10)
    elif dir_hit == 'UP':
        character.y += 25
        character.x += randint(-10,10)
    elif dir_hit == 'DOWN':
        character.y -= 25
        character.x += randint(-10,10)
    else:
        pass

    return character

def handle_player_movement(keys_pressed,character):
    if keys_pressed[pygame.K_a] == True:
        temp_rect = pygame.Rect(character.x - VELO, character.y, character.size_x, character.size_y)
        if ( character.x - VELO ) < 0 or temp_rect.colliderect(NOGO):
            character = colide_animation(character,'LEFT')
        else:
            character.x -= VELO
    if keys_pressed[pygame.K_d] == True:
        temp_rect = pygame.Rect(character.x +  VELO, character.y, character.size_x, character.size_y)
        if ( character.x + VELO ) > WIDTH - character.size_x or temp_rect.colliderect(NOGO):
            character = colide_animation(character,'RIGHT')
        else:
            character.x += VELO
    if keys_pressed[pygame.K_w] == True:
        temp_rect = pygame.Rect(character.x , character.y - VELO, character.size_x, character.size_y)
        if (character.y - VELO ) < 0 or temp_rect.colliderect(NOGO):
            character = colide_animation(character,'UP')
        else:
            character.y -= VELO
    if keys_pressed[pygame.K_s] == True:
        temp_rect = pygame.Rect(character.x , character.y + VELO, character.size_x, character.size_y)
        if (character.y + VELO) > HEIGHT - character.size_y or temp_rect.colliderect(NOGO):
            character = colide_animation(character,'DOWN')
        else:
            character.y += VELO
    character.actor_rect = pygame.Rect(
        character.x, character.y, character.size_x, character.size_y
    )

def main():
    clock = pygame.time.Clock()
    run = True

    main_character = game_actor(
        name ='GREG',
        image_location='/Users/gregsilverstein/Source/Underfoot/Underfoot/assets/SampleAssets/2D/view-Ortho/images/char01_0001.png',
        x=200,
        y=200,
        size_x=50,
        size_y=50,
        actor_rect = pygame.Rect(
            200, 200, 50, 50
        )
    )

    char_list = [main_character]

    while run:
        clock.tick(FPS)
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                run = True
        keys_pressed = pygame.key.get_pressed()
        for character in char_list:
            character = handle_player_movement(keys_pressed,character)
        draw_window(char_list)
        char_list
    pygame.quit()

# Cell
if __name__ == "__main__":
    main()